spring:
  application:
    name: spring-boot-demo
  devtools:
    restart:
      enabled: true

  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://49.232.45.80:3306/employees?serverTimezone=UTC&characterEncoding=utf-8
    driverClassName: com.mysql.jdbc.Driver
server:
  port: 9090
  tomcat:
    uri-encoding: UTF-8
debug: false